# fly.toml app configuration file generated for solace-note-app on 2023-08-15T16:56:38-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solace-note-app"
primary_region = "sea"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
